name: wanandroid_flutter
description: 玩Android - Flutter版

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# Read more about versioning at semver.org.
version: 1.0.0+1

environment:
  sdk: ">=2.0.0-dev.68.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2
  # 吐司
  fluttertoast: ^2.2.7
  # http 网络框架
  http: ^0.12.0
  # dio 网络框架
  dio: ^1.0.13
  # eventbus
  event_bus: ^1.0.1
  # 广告banner
  flutter_swiper: ^1.1.4
  # 缓存image
  cached_network_image: ^0.5.1
  # 查看图片 
  photo_view: ^0.1.2
  url_launcher: ^4.0.3
  # 上拉加载和下拉刷新的组件
  pull_to_refresh: ^1.1.6
  # 常用工具类库 https://github.com/Sky24n/common_utils
  common_utils: ^1.0.9
  # # flustars(Flutter 常用工具类库)
  # flustars:
  #   git:
  #     url: git://github.com/yangxiaoge/flustars.git
  #     #path: /
 
  # flutterchina flukit
  # flukit:
  #   git:
  #     url: git://github.com/flutterchina/flukit.git
  #     path: package_src/
  
  # flutter_webview_plugin
  flutter_webview_plugin: ^0.3.0+2
  # flutter_plugins(里面有众多插件可以引用，如下 webview_flutter，share等)
  # webview_flutter: #（https://github.com/yangxiaoge/plugins/  packages/webview_flutter/ ,packages下有很多的库，需要指定才能用）
  #   git:
  #     url: git://github.com/yangxiaoge/plugins.git
  #     ref: newDev
  #     path: packages/webview_flutter/
  # 分享（调用系统分享的 Flutter 组件，支持分享文本，图片和文件）
  share: #（https://github.com/yangxiaoge/plugins/  packages/webview_flutter/ ,packages下有很多的库，需要指定才能用）
    git:
      url: git://github.com/yangxiaoge/plugins.git
      ref: newDev
      path: packages/share/
 
 
dev_dependencies:
  flutter_test:
    sdk: flutter


# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg

  assets:
  #  - assets/images/zz.png
   - android/app/src/main/res/mipmap-xhdpi/zz.png
   - assets/images/weather_bg.jpg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.io/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.io/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.io/custom-fonts/#from-packages
  
# https://www.iconfont.cn/manage/index?manage_type=myprojects&projectId=979981
  fonts:
    - family: aliIconFont
      fonts:
        - asset: assets/fonts/iconfont.ttf

    - family: WorkSansMedium
      fonts:
        - asset: assets/fonts/WorkSans-Medium.ttf